### ISSUE TITLE
Other Cluster-Buster source code repo.

### ISSUE THREAD

**Issue by ghuls** [weng-lab/cluster-buster#1]
Hi,

My import of the original Cluster-Buster source code with some modification to make it a bit faster can be found here:
https://github.com/ghuls/clusterbuster

  - Do not print version info at the start, but at the end.
  - Add "-V" option to only print the version (git commit date and ID).
  - Do not print sequence names which is being scanned by default:
    - Add "-v" (verbose) option which will revert to the old behavior.'
    - When scanning several thousand regions of around 1kb, it saves 10% of the running time.
  - Change "endl" to newlines so not each line is flushed immediately.
  - Reformatted all source code files with clang-format.
  - Compile binaries with "-march=native" switch and provide option to compile with intel compiler.
    - This allows to use faster instructions (like AVX2 to be used for log1p, exp and log) which can speedup Cluster-Buster up to 60% compared with the original version).

**Comment by purcaro** [comment]
Hi!
This is great! Would you be able to branch from our master branch here, apply your changes, then make a pull request? We can easily accept it, then.

Best!
Michael

**Comment by ghuls** [comment]
It would save me a lot of work if you could clone my repo and force push it to this one, else I have to reapply all commits. There are no (github) forks of this repo at the moment, so it should be fine.
As far as I can tell there is now nothing is this repo that is not in mine.
Once this repo contains the code from my repo, I will remove my repo.

```
# Clone my repo:
git clone https://github.com/ghuls/clusterbuster.git

# Add a new remote (this repo):
git remote add weng_lab_cluster_buster https://github.com/weng-lab/cluster-buster.git

# Force push to this repo:
git push -f weng_lab_cluster_buster master
```

In my commit messages I also described from where the original source code was found and which commands were run before it was committed to git:
https://github.com/ghuls/clusterbuster/commits/master

**Comment by purcaro** [comment]
I 'git cherry-pick'ed your commits after the initial import. We'd definitely like more improvements, and hope to see some pull requests! We are also changing the website to link directly to this GitHub. Thanks!

**Comment by purcaro** [comment]
Also--I added a collaborators to the README; please add your email if you like!

**Comment by ghuls** [comment]
hulselmansgert ATgmail.com
