### ISSUE TITLE
Does cluster-buster check also the reverse complemented strand?

### ISSUE THREAD

**Issue by daxus4** [weng-lab/cluster-buster#6]
Hello, I need a clarification about the input fasta file.

I have to use [create_cistarget_databases](https://github.com/aertslab/create_cisTarget_databases), that use cluster-buster in order to create a region rank for each motif.

I obtain the fasta file that I will give to cluster-buster, by converting a bed file, which also have the strand field, with `bedtools getfasta`.
With bedtools you can specify, with the parameter -s, that if the feature occupies the antisense strand, the sequence will be reverse complemented.

My question is: when I convert the bed to fasta, I have to use the -s parameter or cluster-buster check automatically also the reverse complemented strand and so it is not essential to pass the right strand sequence?

Thanks for your help!

**Comment by ghuls** [comment]
Cluster-Buster scans the sequence in both directions.

So use `bedtools getfasta` without the strand option.

You can generate a BED file with the CRMs and motif matches.

```bash
cbust -f 5 -c 0.0 -m 5.0 -r 10000 -b 0 -t 1 -G 0 motif.cb regions.fa > CRMs_and_motifs.bed
```

**Comment by daxus4** [comment]
Ok, thank you ghuls, it's very helpful :)
